### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by sky-dot-net** [DiNitride/Discord-Music-Status#40]
Hey, i get the following Error

> [2017-12-26 14:02:23.636093] DEBUG: Discord Music: Loading config files
[2017-12-26 14:02:23.636594] INFO: Discord Music: Config loaded
Traceback (most recent call last):
  File "C:\Users\...\Desktop\Discord-Music-Status-master\Discord-Music-Status-master\run.py", line 62, in <module>
    bot = commands.Bot(command_prefix=['m.'], self_bot=True)
  File "C:\Users\...\Anaconda3\lib\site-packages\discord\ext\commands\bot.py", line 207, in __init__
    super().__init__(**options)
  File "C:\Users\...\Anaconda3\lib\site-packages\discord\ext\commands\core.py", line 452, in __init__
    super().__init__(**kwargs)
  File "C:\Users\...\Anaconda3\lib\site-packages\discord\client.py", line 142, in __init__
    self.loop = asyncio.get_event_loop() if loop is None else loop
  File "C:\Users\...\Anaconda3\lib\asyncio\events.py", line 676, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\...\Anaconda3\lib\asyncio\events.py", line 584, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-1'.

is your tool incomaptible to anaconda?

**Comment by DiNitride** [comment]
It has never been tested with Anaconda, so I cannot say whether it is or not, it has only been tested with Python 3.6+.
