### ISSUE TITLE
"No such file or directory" despite completely correct path in config.ini

### ISSUE THREAD

**Issue by FunctionDJ** [DiNitride/Discord-Music-Status#45]
My config.ini: 
```
[Config]
token = [token]
snip = C:\Users\MyName\Desktop\temp\Snip.txt
```
Console output:
```
C:\Users\MyName\Desktop\temp\DiscordMusicStatus>python run.py
[2018-01-06 21:25:08.877429] DEBUG: Discord Music: Loading config files
[2018-01-06 21:25:08.880429] INFO: Discord Music: Config loaded
[2018-01-06 21:25:08.881930] INFO: Discord Music: Logging in
[2018-01-06 21:25:15.817797] INFO: Discord Music: Logged in as waffeln with ID [ID]
[2018-01-06 21:25:15.818297] INFO: Discord Music: Ready to start
Task exception was never retrieved
future: <Task finished coro=<music_loop() done, defined at run.py:80> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "run.py", line 85, in music_loop
    song = pull_song()
  File "run.py", line 102, in pull_song
    with open(snip, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MyName\\Desktop\\temp\\Snip.txt'
```
Running Python 3.6.4, just freshly installed discord.py and logbook

**Comment by DiNitride** [comment]
Is Snip running and has the file been created?

**Comment by FunctionDJ** [comment]
yes to both. snip is running as expected. looking at the error it seems to be an internal formatting issue because of the double slashes //.

**Comment by DiNitride** [comment]
Double slashes are normal, try moving it to a location that isn't your desktop and try there.
